default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy-environment_development
  host: localhost

test:
  <<: *default
  database: easy-environment_test

production:
  <<: *default
  database: easy-environment_production
  username: easy-environment
  password: <%= ENV['EASY-ENVIRONMENT_DATABASE_PASSWORD'] %>
